---
- name: install dependencies
  package:
    name: "{{item}}"
    state: installed
  with_items:
    - python
    - python-pip

- name: install virtualenv
  pip:
    name: virtualenv

- name: install requirements.txt
  pip:
    requirements: "{{rtbstats_path}}/requirements.txt"
    virtualenv: "{{rtbstats_path}}/venv"
    virtualenv_python: "{{rtbstats_python_version}}"