---
- name: django manage migrate
  django_manage:
    command: migrate
    app_path: "{{rtbstats_path}}"
    virtualenv: "{{rtbstats_path}}/venv"
    settings: "config.{{rtbstats_settings}}"

- name: django manage createcachetable
  django_manage:
    command: createcachetable rtb_cache_table
    app_path: "{{rtbstats_path}}"
    virtualenv: "{{rtbstats_path}}/venv"
    settings: "config.{{rtbstats_settings}}"

- name: django manage createsuperuser
  django_manage:
    command: createsuperuser
    app_path: "{{rtbstats_path}}"
    virtualenv: "{{rtbstats_path}}/venv"
    settings: "config.{{rtbstats_settings}}"

- name: django manage crontab add
  django_manage:
    command: crontab add
    app_path: "{{rtbstats_path}}"
    virtualenv: "{{rtbstats_path}}/venv"
    settings: "config.{{rtbstats_settings}}"