---
- name: uwsgi ini file
  template:
    src: uwsgi.j2
    dest: "/etc/uwsgi/{{rtbstats_appname}}.ini"
    owner: "{{rtbstats_user}}"
    mode: 0644

- name: uwsgi service file
  template:
    src: uwsgi.service.j2
    dest: "/etc/systemd/system/{{rtbstats_appname}}.service"
    owner: root
    mode: 0644
  notify: Reload systemd service file


- name: Start UWSGI service
  service: 
    name:  "{{rtbstats_appname}}"
    state: started 
    enabled: yes