---
caddy_vhosts:
  - name: stats.rtb.cat
    urls: stats.rtb.cat:80
    root: /var/www/stats.rtb.cat
    fastcgi: 
      - path: /
        target: /run/caddy/stats.rtb.cat.sock
        params:
          except: /client /client/dist
    rewrite:
      - from: /
        to: "{path} {path}/ /index.php/{query}"